spring.application.name=segrego-backend

spring.datasource.url=jdbc:mysql://localhost:3307/segrego_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=U2VncmVHb1NlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTA=
app.jwt.expiration=86400000
app.seed-data=false
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
